version: '3'
services:
  ap2n-db:
    #api-server db
    platform: linux/x86_64 # m1チップ対策
    image: mysql:5.7
    container_name: ap2n-db
    networks:
      - ap2nnet
    volumes:
      - ap2n-db-vol:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d # 初期sql実行
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ap2n
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  ap2n-server:
    #api-server
    depends_on:
      - ap2n-db
    image: george9971/ap2n:latest
    container_name: ap2n-server
    networks:
      - ap2nnet
    volumes:
      - ./upload:/usr/src/app/ApocalypseNow/api-server/upload # アップロード画像
      - ./undetect:/usr/src/app/ApocalypseNow/api-server/undetect # 未検出画像 yolo精度向上のためバインドする
    working_dir: /usr/src/app/ApocalypseNow/api-server/
    tty: true #バックグラウンドで起動     
    shm_size: '2gb' #メモリ不足で落ちる対策
    ports:
      - 8000:8000 #api-server用
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia # GPU対応
              count: 1
              capabilities: [ gpu ]
networks:
  ap2nnet:
volumes:
  ap2n-db-vol:
